### ISSUE TITLE
Basic Gamification - Tracking User Engagement

### ISSUE THREAD

**Issue by meganyyu** [meganyyu/Prolific#60]
- [x] Set up system to update karma for user easily

These engagement factors go through a function to generate your karma:
- [x] submit a snippet: +0.1 karma
- [x] voting on a snippet: +0.1 karma
- [x] winning a round: +5.0 karma
~- [ ] viewing projects: 0.01 x user karma (but only up to 100 views)~
- [x] compose a starter project: +3.0 karma
- [x] complete a badge: +10.0 karma

Purpose of karma
- Votes of users without much karma is worth very little
- Power of a user's vote is # votes x karma
- If a user votes for multiple snippets in a round then the weight of their vote is divided proportionately by the number of votes the user makes
