### ISSUE TITLE
Basic Gamification - Badge System

### ISSUE THREAD

**Issue by meganyyu** [meganyyu/Prolific#67]
## Tasks
- [x] Design basic badges on paper and design schema
- [x] Create Badge model and model builder classes on client side
- [x] Add DAO methods that can fetch or update badge data from server side
- [x] Set up ProfileVC to load badge data
- [x] Implement some of the basic badges

## Basic badges:
- [x] Contributor Badge: submit 50 snippets per level
- [x] Big Hit Writer Badge: win 20 rounds
    - will have to implement this later, once Cloud Functions are set up
- [x] Creator Badge: compose 20 projects per level (later on, change so that the higher level you are, the more projects you have to compose)

## Adding to Cloud Firestore's Users documents
Note: **bold** text indicates a collection, *italicized* text indicates a document.

**users**
- *user 1*
    - other user metadata
    - **badges**
        - *contributor-badge*
            - level
            - goalCompletedSoFar: amount completed so far for level
            - totalGoal: total amount needed to complete level
        - *big-hit-writer-badge*
            - ...
        - *creator-badge*
            - ...
